<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/Auth.php';
exigirAdmin();
function ejecutarIpconfig(): string { return shell_exec('ipconfig /all 2>&1') ?? ''; }
function detectarInterfaces(string $salida): array { $interfaces=[];$bloques=preg_split('/(?=^\s*(?:Adaptador|Adapter)\s+)/mi',$salida);foreach($bloques as $bloque){if(trim($bloque)==='')continue;$nombre='';if(preg_match('/^\s*(?:Adaptador|Adapter)\s+(.*?):\s*$/mi',$bloque,$m))$nombre=trim($m[1]);$ip=null;if(preg_match('/IPv4[^:]*:\s*([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/i',$bloque,$m))$ip=$m[1];$interfaces[]=['nombre'=>$nombre,'ip'=>$ip,'wifi'=>(bool)preg_match('/wi[\s-]?fi|wifi|inal[aá]mbrica|wireless/i',$nombre.' '.$bloque),'activo'=>$ip!==null];}return $interfaces; }
$wifi=null;foreach(detectarInterfaces(ejecutarIpconfig()) as $interfaz){if($interfaz['wifi']&&$interfaz['activo']&&filter_var($interfaz['ip'],FILTER_VALIDATE_IP,FILTER_FLAG_IPV4)){$wifi=$interfaz;break;}}
$urlMovil=$wifi?'https://'.$wifi['ip'].'/movil':'';
?>
<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Red - Songa Eventos</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f4f6f8;color:#1f2937;padding:30px}.contenedor{max-width:1050px;margin:auto}.volver{display:inline-block;margin-bottom:18px;color:#2563eb;text-decoration:none;font-weight:bold}.card{background:#fff;border-radius:14px;padding:28px;box-shadow:0 3px 15px rgba(0,0,0,.08)}h1{margin:0 0 22px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:35px;align-items:center}.ok{color:#198754;font-size:20px;font-weight:bold}.dato{margin:16px 0;font-size:17px}.ip{font-size:36px;font-weight:bold;color:#1769d1;margin:8px 0 24px}.url{background:#eef5ff;padding:16px;border-radius:9px;font-size:19px;word-break:break-all;color:#1769d1;font-weight:bold}.qr{text-align:center}.qrbox{display:inline-flex;background:#fff;padding:20px;border:1px solid #dbe3ec;border-radius:12px;min-width:320px;min-height:320px;align-items:center;justify-content:center}.qrbox img{width:280px;height:280px;display:block}.aviso{color:#856404;background:#fff3cd;border:1px solid #ffecb5;border-radius:8px;padding:12px;max-width:420px}.error{color:#dc3545;font-weight:bold;font-size:18px}@media(max-width:750px){body{padding:15px}.grid{grid-template-columns:1fr}.qrbox{min-width:280px;min-height:280px}.qrbox img{width:250px;height:250px}}</style></head><body><div class="contenedor"><a href="eventos.php" class="volver">← Volver a eventos</a><div class="card"><h1>🌐 Red Songa Eventos</h1><?php if($wifi):?><div class="grid"><div><p class="ok">✓ Interfaz Wi-Fi detectada</p><div class="dato"><strong>Adaptador:</strong> <?=htmlspecialchars($wifi['nombre'])?></div><div class="dato"><strong>IP:</strong></div><div class="ip"><?=htmlspecialchars($wifi['ip'])?></div><h3>📱 Acceso desde PDA / celular</h3><div class="url"><?=htmlspecialchars($urlMovil)?></div><p>Conecta el PDA o celular a la misma red Wi-Fi y escanea el código QR.</p></div><div class="qr"><h2>📷 Escanea para acceder</h2><div class="qrbox"><?php if($wifi['ip']==='192.168.1.90'):?><img src="/img/qr_movil.svg" alt="Código QR para <?=htmlspecialchars($urlMovil)?>"><?php else:?><div class="aviso">El QR de prueba está generado para 192.168.1.90. La IP actual es <?=htmlspecialchars($wifi['ip'])?>.</div><?php endif;?></div><p>El código abrirá directamente el sitio móvil de Songa Eventos.</p></div></div><?php else:?><p class="error">✗ No se encontró una interfaz Wi-Fi activa.</p><p>Verifica que el equipo esté conectado al Wi-Fi del TCL LINKZONE.</p><?php endif;?></div></div></body></html>
